apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  selector:
    app: telegraf
  type: NodePort
  ports:
    - protocol: TCP
      port: 42518
      targetPort: 42518
      nodePort: 30518  # Define un puerto dentro del rango 30000-32767