apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      flush_interval = "10s"
      hostname = "telegraf"

    [[inputs.cisco_telemetry_mdt]]
      transport = "grpc"
      service_address = ":42518"

    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "telegraf"